### ISSUE TITLE
Add an example of usage in README.md

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/simple-date-validator#1]
Add a sample code of the usage of library in the README.md file

**Comment by leeyspaul** [comment]
Hey @arshadkazmi42. Can I pick up this issue to? 

Can you give me an example? I'm going to run it on my own too but just wanted to hear from you as well! Thanks!

**Comment by arshadkazmi42** [comment]
Yes, Go ahead and create a PR

For this, basically `how to use` tilte needs to be added in readme and a sample usage code below the title.

There is sample usage given in the test file here

https://github.com/arshadkazmi42/simple-date-validator/blob/master/test/index.js

it will look something like this

https://github.com/arshadkazmi42/ak-logger#how-to-use

You can give it a try, let me know if you need any other help.

**Comment by arshadkazmi42** [comment]
@leeyspaul Let me know, if you need any help with this.

**Comment by leeyspaul** [comment]
I was able to replicate the usage, I'm going to put in a PR now. Let me know if I did something wrong and I'll fix it up right away. :)

**Comment by arshadkazmi42** [comment]
Thank you for working on this @leeyspaul
