### ISSUE TITLE
Moving all the test dependencies to dev-dependencies in package.json

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/simple-date-validator#10]
**Describe the bug**
Currently all the test dependencies are added in dependencies object in package.json

**Expected behavior**
All the test related dependencies should reside in dev-dependencies object of package.json

**Additional context**
To fix this, chai & mocha these two dependencies are for testing purpose, so these should be moved to dev-dependencies of package.json

There is a detailed explanation of package.json file here
https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies

**Comment by leeyspaul** [comment]
Hi @arshadkazmi42 ! Could I take up this issue? Thank you!

**Comment by arshadkazmi42** [comment]
@leeyspaul, go for it.

**Comment by leeyspaul** [comment]
I believe everything is okay and it is what was needed. If there are any issues please do let me know. Thank you!

**Comment by arshadkazmi42** [comment]
Thank you @leeyspaul for taking this up

**Comment by arshadkazmi42** [comment]
@leeyspaul since you have started contributing to this repo, why don't you go ahead and add yourself in contributors list mentioned in #9

**Comment by leeyspaul** [comment]
@arshadkazmi42 will do!

**Comment by leeyspaul** [comment]
I think I did it correctly but not sure. New to Git sorry haha. If there's any issues let me know! I'd also be happy to take up issue #4 as well!

**Comment by arshadkazmi42** [comment]
@leeyspaul looks good, just 1 thing, try to name branch as per the change you are going to do. other than that everything looks good.
Also go ahead for #4 
You can comment on that issue that you are working on it. and go for it, open a PR 👍

**Comment by leeyspaul** [comment]
@arshadkazmi42 Yeah of course I'll do that. So I should open up and name the branch accordingly for every issue right?

**Comment by arshadkazmi42** [comment]
@leeyspaul yes.
