### ISSUE TITLE
Change var to const

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/simple-date-validator#17]
**Describe the bug**
Change all the `var` to `const` in index.js

**Additional context**
All the variables defined as `var` should be changed to `const` in index.js file

https://github.com/arshadkazmi42/simple-date-validator/blob/master/index.js

**Comment by codingnninja** [comment]
claim

**Comment by arshadkazmi42** [comment]
@codingnninja Cool. Go ahead and create a PR. Let me know if you need any other information

**Comment by codingnninja** [comment]
@arshadkazmi42  I don't seem to understand this very well:

To Reproduce
Steps to reproduce the behavior: NA

Expected behavior
NA

Screenshots
NA

Desktop (please complete the following information):

OS: [e.g. iOS]
Browser [e.g. chrome, safari]
Version [e.g. 22]
Additional context
All the variables defined as var should be changed to const in index.js file

I want to understand this before I PR

**Comment by arshadkazmi42** [comment]
@codingnninja That was issue template. I have updated the issue description you can check it now.

**Comment by codingnninja** [comment]
@arshadkazmi42  I have made a PR. Also, can I take on other issues after this one is completed? Best regards.

**Comment by arshadkazmi42** [comment]
@codingnninja Thank you for working on this.
You can tag this issue in your PR description using `#17` without the code tags

**Comment by moogacs** [comment]
@arshadkazmi42  Are this one is done ?

**Comment by arshadkazmi42** [comment]
@moogacs @codingnninja was working on this, he has worked on it, but I just needed some confirmation whether the existing test cases are passing or not. 

I would like to wait for 1-2 days more if he turns up, after that I will open it for grabs

**Comment by arshadkazmi42** [comment]
@moogacs you can take a look at other issues we have

**Comment by ahhmarr** [comment]
[https://github.com/arshadkazmi42/simple-date-validator/pull/20](#20 )

**Comment by wptechprodigy** [comment]
Is it open now?
