### ISSUE TITLE
Add Code Quality Badge

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/simple-date-validator#24]
**Describe the bug**
Add Code Quality Badge to README

**Additional context**

Add Code Quality badge next to downloads badge in README file

just copy the below code and add it in readme below downloads code 

`[![Codacy Badge](https://api.codacy.com/project/badge/Grade/12b4f952ec1e497e8d2c2f88638672f5)](https://www.codacy.com/app/arshadkazmi42/simple-date-validator?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=arshadkazmi42/simple-date-validator&amp;utm_campaign=Badge_Grade)`

**To work on this**
1. Put a comment here who ever is working on it.
2. Also tag this issue in your Pull Request description.
Anyone who is not following above two steps, their PR will be rejected

**Comment by NefixEstrada** [comment]
I'm doing this

**Comment by NefixEstrada** [comment]
Nvm, just saw the first-timers-only badge

**Comment by arshadkazmi42** [comment]
@NefixEstrada Cool. goAhead and create a PR.
Do read the notes at the bottom of the issue

**Comment by adventuroussrv** [comment]
Hi I'm doing this

**Comment by arshadkazmi42** [comment]
@NefixEstrada Opening it for first timers of the Repo, if its your first PR for this repo, then go ahead and work on this.

**Comment by roebuk** [comment]
Hi,

I'll happily take this 👍

**Comment by arshadkazmi42** [comment]
@roebuk @NefixEstrada has shown interest first on this, we will wait for them to reply for sometime, if they do not come back, then you can work on it. Keep a track on this issue, you are second in the queue :)

**Comment by roebuk** [comment]
@arshadkazmi42 sounds good to me 👍

**Comment by jcat1504** [comment]
Hi, I'll do this :)

**Comment by arshadkazmi42** [comment]
@jcat1504 @roebuk approached here first. So I will give first priority to @roebuk PR, 
@roebuk If you are interested you can work on it, otherwise @jcat1504 has already opened a PR if you are fine with it, I will go ahead with her PR

**Comment by roebuk** [comment]
Hey I've attached my PR over here 

https://github.com/arshadkazmi42/simple-date-validator/pull/26

**Comment by NefixEstrada** [comment]
Go ahead and merge it, it's not an issue for me :D

**Comment by arshadkazmi42** [comment]
> Go ahead and merge it, it's not an issue for me :D

Thanks @NefixEstrada

**Comment by arshadkazmi42** [comment]
> Hey I've attached my PR over here
> 
> #26

@roebuk I have added a small comment in PR. Can you make that change
