### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/simple-date-validator#3]
Add a gitignore file to the code base. 
For this basically add gitignore to remove IDE specific config files and node_modules

**Comment by a-santos** [comment]
Can I take this?

**Comment by arshadkazmi42** [comment]
@a-santos yes, go ahead.

**Comment by a-santos** [comment]
I will commit this weekend

**Comment by arshadkazmi42** [comment]
Cool 👍

**Comment by a-santos** [comment]
@arshadkazmi42 I'm sorry for having responded in good time. I hope I can help another opportunity

**Comment by arshadkazmi42** [comment]
@a-santos Cool. go ahead and explore the other issues.
