### ISSUE TITLE
Code indentation

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/simple-date-validator#4]
At present the code in index.js is not aligned properply. Add proper indentation to the code

**Comment by leeyspaul** [comment]
Working on this issue!

**Comment by arshadkazmi42** [comment]
Thank you for taking this up @leeyspaul 
Go ahead and create a PR

**Comment by leeyspaul** [comment]
Awesome. For this one I have a question. Should I be following this whitespace indentation for all? Example: `isValidDate: function ( date, dateFormat ) {` where there is whitespace between the function declaration and same for parameters? Also I noticed the same thing with the conditionals. New to JS Syntax.  @arshadkazmi42

**Comment by arshadkazmi42** [comment]
yes this will do. also we need 2 space indentation for all lines before starting, i think at present its using 4 spaces indentation on every line starting, we need it to be changed to 2 spaces

**Comment by arshadkazmi42** [comment]
if you are using VS Code IDE then its easy to do indentation, you have to set the indentation to 2 spaces from right bottom corner, then just press ALT + SHIFT + F and in mac OPTION + SHIFT + F

**Comment by leeyspaul** [comment]
Ahh using Atom, haha.

**Comment by arshadkazmi42** [comment]
I think Atom also should be having some feature like that, every IDE has auto indentation.

**Comment by leeyspaul** [comment]
Er just spotted an indentation error. Going to fix and re-PR.
