### ISSUE TITLE
Add function to check past dates

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/simple-date-validator#5]
Add a function to check whether the input date is past or not.
You can take date && date format as input and check based on that.
This is my suggestion.

If you got any suggestion feel free to post here and create a PR

Also, add test case to verify the functionality

**Comment by leeyspaul** [comment]
Hey @arshadkazmi42 I can pick this up! Is the functionality we want to simply return a boolean to check whether a date input is past current date or not?

**Comment by arshadkazmi42** [comment]
@leeyspaul Yes. Thats correct. You can work on it. Also we need a test to validate it.
Let me know if you need any other information.

**Comment by leeyspaul** [comment]
Okay I think I got it, going to create the PR now.

**Comment by arshadkazmi42** [comment]
@leeyspaul Thank you for working on this.
