### ISSUE TITLE
Add yourself to Contributors.md

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/simple-date-validator#9]
If you are starting with opensource contributions, this is best to start with.
just go ahead and add your details to Contributors.md file in the same format as other's details.

**Comment by hiteshpr** [comment]
Hi, can I work on this?

**Comment by arshadkazmi42** [comment]
@hiteshpr This is for everyone. Anyone who wants to start contribution or contributes to this project should add themselves to this file.

So, go ahead and create a PR

**Comment by ahhmarr** [comment]
[#21](https://github.com/arshadkazmi42/simple-date-validator/pull/21)
